### PR TITLE
Speedupcmakeinstall to wisk

### PR DESCRIPTION
**Pull request by ivan-kulikov-dev**

### CODE REVIEW

**Comment by ivan-kulikov-dev** [comment]
testing_emulation test is broken?(the test is performed for a long time)

**Comment by ivan-kulikov-dev** [comment]
Build time (20 min)

**Comment by wisk** [comment]
Thank you for your fix, it was added to the branch dev. :)
Does it matter if your used account is **gunmetalbackupgooglecode** instead of **gunmetal313**?

**Comment by ivan-kulikov-dev** [comment]
All ok :)

**Pull request closed without merging**
